CREATE TABLE dbo.Images
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Images PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	ContentType NVARCHAR(255) NOT NULL,
	Content VARBINARY(MAX) NOT NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Images_CreateDate DEFAULT SYSDATETIME()
)
