CREATE TABLE dbo.MessageReplies
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_MessageReplies PRIMARY KEY,
	MessageId INT NOT NULL CONSTRAINT FK_MessageReplies_MessageId FOREIGN KEY REFERENCES dbo.Messages(Id),
	UserId INT NOT NULL CONSTRAINT FK_MessageReplies_UserId FOREIGN KEY REFERENCES dbo.Users(Id),
	Content NVARCHAR(MAX) NOT NULL,
	LastUpdate DATETIME2(0) NOT NULL CONSTRAINT DF_MessageReplies_LastUpdate DEFAULT SYSDATETIME(),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_MessageReplies_CreateDate DEFAULT SYSDATETIME()
)
