CREATE TABLE dbo.Plugins
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Plugins PRIMARY KEY,
	BranchId INT NOT NULL CONSTRAINT FK_Plugins_BranchId FOREIGN KEY REFERENCES dbo.Branches(Id),
	Version VARCHAR(255) NOT NULL,
	Changelog NVARCHAR(2000) NULL,
	FileName NVARCHAR(255) NOT NULL,
	Data VARBINARY(MAX) NOT NULL,
	IsEnabled BIT NOT NULL CONSTRAINT DF_Plugins_IsEnabled DEFAULT 0,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Plugins_CreateDate DEFAULT SYSDATETIME()
)
