CREATE TABLE dbo.ProductTags
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_ProductTags PRIMARY KEY,
	Title NVARCHAR(255) NOT NULL CONSTRAINT UK_ProductTags_Title UNIQUE,
	Color NVARCHAR(7) NOT NULL CONSTRAINT DF_ProductTags_Color DEFAULT '#6c757d',
	BackgroundColor NVARCHAR(7) NOT NULL CONSTRAINT DF_ProductTags_BackgroundColor DEFAULT '#ebebef',
)
