CREATE TABLE dbo.ProductTabs
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_ProductTabs PRIMARY KEY,
	ProductId INT NOT NULL CONSTRAINT FK_ProductTabs_ProductId FOREIGN KEY REFERENCES dbo.Products(Id),
	Title NVARCHAR(30) NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	IsEnabled BIT NOT NULL CONSTRAINT DF_ProductTabs_IsEnabled DEFAULT 0
)
