CREATE TABLE dbo.Users
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Users PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	Role VARCHAR(255) NOT NULL,
	SteamId CHAR(17) NOT NULL,
	AvatarImageId INT NULL CONSTRAINT FK_Users_AvatarImageId FOREIGN KEY REFERENCES dbo.Images(Id),
	Color VARCHAR(255) NULL,
	Avatar VARBINARY(MAX) NULL,
	PayPalEmail NVARCHAR(255) NULL,
	PayPalCurrency CHAR(3) NOT NULL CONSTRAINT DF_Users_PayPalCurrency DEFAULT 'USD',
	DiscordWebhookUrl NVARCHAR(255) NULL,
	TermsAndConditions NVARCHAR(4000) NULL,
	Biography NVARCHAR(4000) NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Users_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT UK_Users_SteamId UNIQUE (SteamId)
)
